{% set name = "gym-ignition-models" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gym_ignition_models-{{ version }}.tar.gz
  sha256: e4e30488988f1ca2efa844d676633241b3d93ac194129cf2114ff7e6075b3e8f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - gym_ignition_models
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robotology/gym-ignition-models
  summary: Collection of robot models for the Ignition Gazebo simulator
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - diegoferigo
